title: .plan file
description: [This is a daily status update for myself. It's intended purpose is to keep me focused or at least document my day when I am focused. (Paintings)[http://www.vivier.net/paintings] ]

show_downloads: ["false"]
google_analytics: [Your Google Analytics tracking ID]

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# More configurations here: https://github.com/pages-themes/minimal?tab=readme-ov-file
